# Generated by Django 4.2.6 on 2023-10-06 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.TextField()),
                ('seq', models.TextField()),
                ('unnormalized_read_counts', models.BigIntegerField()),
                ('isomirmap_flags', models.TextField()),
                ('mintmap_flags', models.TextField()),
                ('minrmap_flags', models.TextField()),
                ('yrfmap_flags', models.TextField()),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
        ),
    ]
