# Generated by Django 4.2.6 on 2023-10-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset234',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.TextField()),
                ('seq', models.TextField(blank=True, null=True)),
                ('unnormalized_read_counts', models.BigIntegerField(blank=True, null=True)),
                ('isomirmap_flags', models.TextField(blank=True, null=True)),
                ('mintmap_flags', models.TextField(blank=True, null=True)),
                ('minrmap_flags', models.TextField(blank=True, null=True)),
                ('yrfmap_flags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset_234',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset282',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.TextField()),
                ('seq', models.TextField(blank=True, null=True)),
                ('unnormalized_read_counts', models.BigIntegerField(blank=True, null=True)),
                ('isomirmap_flags', models.TextField(blank=True, null=True)),
                ('mintmap_flags', models.TextField(blank=True, null=True)),
                ('minrmap_flags', models.TextField(blank=True, null=True)),
                ('yrfmap_flags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset_282',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset343',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.TextField()),
                ('seq', models.TextField(blank=True, null=True)),
                ('unnormalized_read_counts', models.BigIntegerField(blank=True, null=True)),
                ('isomirmap_flags', models.TextField(blank=True, null=True)),
                ('mintmap_flags', models.TextField(blank=True, null=True)),
                ('minrmap_flags', models.TextField(blank=True, null=True)),
                ('yrfmap_flags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset_343',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset355',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.TextField()),
                ('seq', models.TextField(blank=True, null=True)),
                ('unnormalized_read_counts', models.BigIntegerField(blank=True, null=True)),
                ('isomirmap_flags', models.TextField(blank=True, null=True)),
                ('mintmap_flags', models.TextField(blank=True, null=True)),
                ('minrmap_flags', models.TextField(blank=True, null=True)),
                ('yrfmap_flags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset_355',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetDirectory',
            fields=[
                ('dataset_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dataset_directory',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='molecule',
            name='dataset_id',
        ),
        migrations.DeleteModel(
            name='DataSet',
        ),
        migrations.DeleteModel(
            name='Molecule',
        ),
    ]
