# Generated by Django 4.2.6 on 2023-10-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dataset100'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.TextField()),
                ('seq', models.TextField(blank=True, null=True)),
                ('unnormalized_read_counts', models.BigIntegerField(blank=True, null=True)),
                ('isomirmap_flags', models.TextField(blank=True, null=True)),
                ('mintmap_flags', models.TextField(blank=True, null=True)),
                ('minrmap_flags', models.TextField(blank=True, null=True)),
                ('yrfmap_flags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_samples',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Dataset100',
        ),
        migrations.DeleteModel(
            name='Dataset234',
        ),
        migrations.DeleteModel(
            name='Dataset282',
        ),
        migrations.DeleteModel(
            name='Dataset343',
        ),
        migrations.DeleteModel(
            name='Dataset355',
        ),
    ]
